In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Goutham0110/Iris_flower_classification_using_KNN/main/IRIS%20dataset.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
species = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(species)
df['species'] = le.fit_transform(df['species'].astype(str))

In [5]:
#split the data
x = df.drop('species', axis = 1)
y = df['species']
scaler = Normalizer()
X = scaler.fit_transform(x)
X = pd.DataFrame(X, columns = x.columns)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)

KnnModel = KNeighborsClassifier(n_neighbors = 13)
KnnModel.fit(x_train, y_train)
y_pred = KnnModel.predict(x_test)

print("Confusion matrix  : \n", confusion_matrix(y_test, y_pred))
print("\n\nAccuracy score using knn is  :\n ", accuracy_score(y_test, y_pred))

Confusion matrix  : 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


Accuracy score using knn is  :
  0.9777777777777777
